#ifndef COVERAGEDUMMIES_GLOBAL_H
#define COVERAGEDUMMIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COVERAGEDUMMIES_LIBRARY)
#  define COVERAGEDUMMIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COVERAGEDUMMIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COVERAGEDUMMIES_GLOBAL_H
